### ISSUE TITLE
Producer is unable to fetch topic metadata when first kafka broker is down

### ISSUE THREAD

**Issue by vikmv** [ntent-ad/kafka4net#16]
While working on #14, noticed one more issue.

**Steps to reproduce:**
* Prerequisites: 3 kafka brokers (1,2,3)
* Stop 1st kafka broker
* Create producer `new Producer("kafka1,kafka2,kafka3", configuration)`
* Producer is unable to fetch metadata and repeats the error: "Error while trying to fetch topic 'topic_name' metadata, will retry."

My findings why this is happening:

```
//Cluster.ConnectAsync method:
..
initBrokers = ...; // initialized with 3 brokers, and their id=-99
..
MergeTopicMeta(initMeta);   // method is called, and there are still 3 brokers in there
..

//inside MergeTopicMeta method:

var newBrokers = topicMeta.Brokers.Except(_metadata.Brokers, BrokerMeta.NodeIdComparer).ToArray();
//newBroker is left with only 1 record (instead of 3), because all the brokers have the same Id=-99
..
_metadata.Brokers = _metadata.Brokers.Concat(newBrokers).ToArray();
```

So, metadata.Brokers results in adding only one broker to the list and producer is unable to fetch topic metadata from it.

**Comment by vikmv** [comment]
Created pull request #17 with one of possible solutions of this issue

**Comment by vchekan** [comment]
Thanks for reporting this. I fixed it in different manner though. I fixed the comparer, so that if it is used in other placed, this bug would not show up again.
