### ISSUE TITLE
Sample consumer code for multi-topic subscription

### ISSUE THREAD

**Issue by yasirk1** [ntent-ad/kafka4net#32]
Hi there, trying to find sample code for a consumer implementation that has a subscription to multiple topics and automatically commits offsets (either to kafka or other store). 

Also, does this work with the latest version of Kafka ?

**Comment by vchekan** [comment]
At the moment only kafka-0.8 is supported. Updating to newer version should be not too much work, there are just 2 more fields in some of the calls, timestamp of message and throttling time. Probably it is more work in upgrading testing suite than code itself. I've created #34 so you can subscribe and get notification when status change.

I've added examples to the root README.md so people can quick start working with the driver.

Please let me know if you see more use cases deserve to be documented, I'll be glad to help.

**Comment by lihuazhang323** [comment]
I want transfer a big file  , how can i do it ?
